name: Test Workflow

# triggers
on: workflow_dispatch

# jobs
jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print something
        run: echo "Hello World!"
      - name: Next do something
        run: |
            echo "First output"
            echo "Second output"
      - name: Finally do
        run: echo "Say bye!"
